format_version: v1.0
configName: pkobosctest
folderName: mx470osctest
frameworkPath: C:\projects\pic32mx-harmony\harmony-repo
processor: PIC32MX470F512H
projectName: mx470osctest
settings:
  PackageFilter: ''
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  TRUSTZONE: 'false'
  CMSISPath: dev_packs\arm\CMSIS\5.8.0
  MERGE_STRATEGY: USER_ALL
  DFPPath: dev_packs\Microchip\PIC32MX_DFP\1.5.259\atdf\PIC32MX470F512H.atdf
